//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:57:53 AM EDT 
//


package cmsc.splatter.transferobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import cmsc.splatter.transferobjects.reference.IReference;
import cmsc.splatter.transferobjects.reference.IReferencable;
import cmsc.splatter.transferobjects.reference.ReferenceFactory;


/**
 * <p>Java class for connection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requested" type="{}userReference"/>
 *         &lt;element name="requestor" type="{}userReference"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connection", propOrder = {
    "requested",
    "requestor"
})
@XmlRootElement(name = "connection")
public class Connection implements IReferencable {

    @XmlElement(required = true)
    protected UserReference requested;
    @XmlElement(required = true)
    protected UserReference requestor;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the requested property.
     * 
     * @return
     *     possible object is
     *     {@link UserReference }
     *     
     */
    public UserReference getRequested() {
        return requested;
    }

    /**
     * Sets the value of the requested property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserReference }
     *     
     */
    public void setRequested(UserReference value) {
        this.requested = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link UserReference }
     *     
     */
    public UserReference getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserReference }
     *     
     */
    public void setRequestor(UserReference value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    @Override
    public IReference getReference() {
        return ReferenceFactory.getReferenceFactory()
                .getConnectionReference(this);
    }

}
