//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:57:53 AM EDT 
//


package cmsc.splatter.transferobjects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cmsc.splatter.transferobjects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cmsc.splatter.transferobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Requests }
     * 
     */
    public Requests createRequests() {
        return new Requests();
    }

    /**
     * Create an instance of {@link RequestingUser }
     * 
     */
    public RequestingUser createRequestingUser() {
        return new RequestingUser();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link RequestReference }
     * 
     */
    public RequestReference createRequestReference() {
        return new RequestReference();
    }

    /**
     * Create an instance of {@link RequestCollection }
     * 
     */
    public RequestCollection createRequestCollection() {
        return new RequestCollection();
    }

    /**
     * Create an instance of {@link SearchTerms }
     * 
     */
    public SearchTerms createSearchTerms() {
        return new SearchTerms();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link UserReference }
     * 
     */
    public UserReference createUserReference() {
        return new UserReference();
    }

    /**
     * Create an instance of {@link ConnectionReference }
     * 
     */
    public ConnectionReference createConnectionReference() {
        return new ConnectionReference();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link UserCollection }
     * 
     */
    public UserCollection createUserCollection() {
        return new UserCollection();
    }

    /**
     * Create an instance of {@link UserName }
     * 
     */
    public UserName createUserName() {
        return new UserName();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Updates }
     * 
     */
    public Updates createUpdates() {
        return new Updates();
    }

    /**
     * Create an instance of {@link UpdateCollection }
     * 
     */
    public UpdateCollection createUpdateCollection() {
        return new UpdateCollection();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link UpdateReference }
     * 
     */
    public UpdateReference createUpdateReference() {
        return new UpdateReference();
    }

    /**
     * Create an instance of {@link ConnectionCollection }
     * 
     */
    public ConnectionCollection createConnectionCollection() {
        return new ConnectionCollection();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

}
