//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:57:53 AM EDT 
//


package cmsc.splatter.transferobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{}search"/>
 *         &lt;element name="handle" type="{}search"/>
 *         &lt;element name="email" type="{}search"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "handle",
    "email"
})
@XmlRootElement(name = "searchTerms")
public class SearchTerms {

    @XmlElement(required = true)
    protected Search username;
    @XmlElement(required = true)
    protected Search handle;
    @XmlElement(required = true)
    protected Search email;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link Search }
     *     
     */
    public Search getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search }
     *     
     */
    public void setUsername(Search value) {
        this.username = value;
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link Search }
     *     
     */
    public Search getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search }
     *     
     */
    public void setHandle(Search value) {
        this.handle = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link Search }
     *     
     */
    public Search getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link Search }
     *     
     */
    public void setEmail(Search value) {
        this.email = value;
    }

}
