//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:57:53 AM EDT 
//


package cmsc.splatter.transferobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import cmsc.splatter.transferobjects.reference.IReference;
import cmsc.splatter.transferobjects.reference.IReferencable;
import cmsc.splatter.transferobjects.reference.ReferenceFactory;

/**
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{}userName"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userPrivacy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="emailPrivacy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {
    "handle",
    "username",
    "password",
    "email",
    "userPrivacy",
    "emailPrivacy"
})
@XmlRootElement(name = "user")
public class User implements IReferencable {

    @XmlElement(required = true)
    protected String handle;
    @XmlElement(required = true)
    protected UserName username;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String email;
    protected boolean userPrivacy;
    protected boolean emailPrivacy;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandle(String value) {
        this.handle = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link UserName }
     *     
     */
    public UserName getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserName }
     *     
     */
    public void setUsername(UserName value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the userPrivacy property.
     * 
     */
    public boolean isUserPrivacy() {
        return userPrivacy;
    }

    /**
     * Sets the value of the userPrivacy property.
     * 
     */
    public void setUserPrivacy(boolean value) {
        this.userPrivacy = value;
    }

    /**
     * Gets the value of the emailPrivacy property.
     * 
     */
    public boolean isEmailPrivacy() {
        return emailPrivacy;
    }

    /**
     * Sets the value of the emailPrivacy property.
     * 
     */
    public void setEmailPrivacy(boolean value) {
        this.emailPrivacy = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }
    
    /**
     * Gets the full user name
     * @return 
     */
    public String getFullName() {
        return this.username.toString();
    }

    @Override
    public IReference getReference() {
        return ReferenceFactory.getReferenceFactory()
                .getUserReference(this);
    }
}
